[tool.poetry]
name = "tei-collation-converter"
version = "0.1.0"
description = "Converts TEI XML collations to NEXUS and other formats"
authors = ["Joey McCollum and Robert Turnbull"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.7.1"
lxml = "^4.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
