name: beast

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        java-package: 'jdk+fx'
        distribution: 'zulu'
        java-version: '17'
    - name: Install poetry
      run: pipx install poetry
    - name: Install dependencies for Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - run: poetry install
    - name: Testing
      run: |
        poetry run teiphy -t reconstructed -t defective -t orthographic -t subreading -m overlap -m lac -s"*" -s T --fill-correctors example/ubs_ephesians.xml beast_example.xml
    - name: Install Phylogenetics Package
      run: |
        git clone https://github.com/CompEvol/beast2.git
        git clone https://github.com/CompEvol/BeastFX.git
        cd BeastFX
        ant linux
      # cd ~
      # mkdir .beast
      # cd .beast
      # wget https://github.com/CompEvol/beast2/releases/download/v2.7.3/BEAST.v2.7.3.Linux.x86.tgz
      # tar zxvf BEAST.v2.7.3.Linux.x86.tgz
      # ~/.beast/beast/bin/packagemanager -add BEASTLabs
      # ~/.beast/beast/bin/packagemanager -add BDSKY
    - name: Phylogenetics Run
      run: |
        which java
        ls -l
      # ~/.beast/beast/bin/beast beast_example.xml
        